
INSERT INTO PROVIDER (NAME, TIN) VALUES ('MERA',123456);
INSERT INTO PROVIDER (NAME, TIN) VALUES ('MERA2',555555);
INSERT INTO PROVIDER (NAME, TIN) VALUES ('MERA3',777777);
INSERT INTO PROVIDER (NAME, TIN) VALUES ('MERA4',999999);
INSERT INTO PROVIDER (NAME, TIN) VALUES ('MERA5',222222222);

INSERT INTO ITEM (NAME, PRICE, DESCRIPTION) VALUES ('TABLE',156,'BLACK');
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION) VALUES ('DESK',6,'RED');

INSERT INTO WAREHOUSE (NAME, ADDRESS) VALUES ('MAIN_WAREHOUSE','NN, Delovaya Street');
